Effi-BE-fin/src/main/java/com/example/effi/config/TokenProvider.java
Effi-BE-fin/src/main/java/com/example/effi/service/EmployeeService.java

controller service repository 를 통한 로그인 로직 구현, token provider 추가를 통한 로그인 성공 시 토큰 발급

Feat: 로그인 기능 추가

---

Effi-BE-fin/src/main/java/com/example/effi/domain/Group.java
Effi-BE-fin/src/main/java/com/example/effi/domain/GroupEmp.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Participant.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Schedule.java
Effi-BE-fin/src/main/java/com/example/effi/domain/TagSchedule.java
Effi-BE-fin/src/main/java/com/example/effi/domain/TimezoneEmp.java

domain에 mapping부분 추가했습니다. 확인부탁

FEAT: domain mapping add

---

Effi-BE-fin/src/main/java/com/example/effi/config/JwtAuthenticationFilter.java
Effi-BE-fin/src/main/java/com/example/effi/config/SecurityConfig.java

기존에 발급만 되던 토큰을 사용하기 위한 필터와 필터처리에 필요한 기능 추가

Feat : Token Filter 추가

---

Effi-BE-fin/src/main/java/com/example/effi/domain/CategoryDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DeptDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Group.java
Effi-BE-fin/src/main/java/com/example/effi/domain/GroupDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/GroupEmpDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/ParticipantDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/RoutineDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Schedule.java
Effi-BE-fin/src/main/java/com/example/effi/domain/ScheduleDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/TagDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/TagScheduleDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/TimezoneDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/TimezoneEmpDTO.java

employee 제외한 dto 생성함 확인부탁..
employee dto는 @helloyeeun 가..

FEAT: add dto

---

.idea/modules/effi.main.iml
Effi-BE-fin/src/main/java/com/example/effi/controller/EmployeeController.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/CategoryDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/DeptDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/EmployeeDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/GroupDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/GroupEmpDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/ParticipantDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/RoutineDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/ScheduleDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/SignInRequest.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/SignInResponse.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/TagDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/TagScheduleDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/TimezoneDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/TimezoneEmpDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/Category.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/Dept.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/Employee.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/Group.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/GroupEmp.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/Participant.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/Routine.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/Schedule.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/Tag.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/TagSchedule.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/Timezone.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/TimezoneEmp.java
Effi-BE-fin/src/main/java/com/example/effi/repository/EmployeeRepository.java
Effi-BE-fin/src/main/java/com/example/effi/service/EmployeeService.java

RENAME : separate entity and dto

---

Effi-BE-fin/src/main/java/com/example/effi/controller/MyPageController.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/MyPageRequestDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/MyPageResponseDTO.java

EmployeeDTO password 빠져있던 부분 추가

Refactor : EmployeeDTO password

---

Effi-BE-fin/src/main/java/com/example/effi/controller/CategoryController.java
Effi-BE-fin/src/main/java/com/example/effi/repository/CategoryRepository.java
Effi-BE-fin/src/main/java/com/example/effi/repository/ParticipantRepository.java
Effi-BE-fin/src/main/java/com/example/effi/repository/ScheduleRepository.java
Effi-BE-fin/src/main/java/com/example/effi/repository/TagRepository.java
Effi-BE-fin/src/main/java/com/example/effi/service/CategoryService.java
Effi-BE-fin/src/main/java/com/example/effi/service/ParticipantService.java
Effi-BE-fin/src/main/java/com/example/effi/service/ScheduleService.java
Effi-BE-fin/src/main/java/com/example/effi/service/TagService.java

Feat : for schedule func

---

.vscode/settings.json
Effi-BE-fin/src/main/java/com/example/effi/config/JwtAuthenticationFilter.java
Effi-BE-fin/src/main/java/com/example/effi/config/SecurityConfig.java
Effi-BE-fin/src/main/java/com/example/effi/controller/GroupController.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/Group.java
Effi-BE-fin/src/main/resources/application.properties
Effi-BE-fin/src/main/resources/jwt.yaml
Effi-FE-fin/package-lock.json
Effi-FE-fin/package.json
Effi-FE-fin/src/components/EmployeeSearch.vue
Effi-FE-fin/src/components/GroupModal.vue
Effi-FE-fin/src/components/HomeHeader.vue
Effi-FE-fin/src/components/LeftSidebar.vue
Effi-FE-fin/src/views/HomeView.vue

group 예약어라서 테이블명으로 사용할 수 없어서 groups로 변경

Fix: Rename table명 group -> groups

---

Effi-BE-fin/src/main/java/com/example/effi/controller/TagController.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/CategoryResponseDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/RoutineRequestDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/RoutineResponseDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/ScheduleRequestDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/ScheduleResponseDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/TagResponseDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/TagScheduleDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/TagScheduleResponseDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/TagScheduleUpdateDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/Routine.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/Schedule.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/TagSchedule.java
Effi-BE-fin/src/main/java/com/example/effi/repository/RoutineRepository.java
Effi-BE-fin/src/main/java/com/example/effi/repository/TagScheduleRepository.java
Effi-BE-fin/src/main/java/com/example/effi/service/CategoryService.java
Effi-BE-fin/src/main/java/com/example/effi/service/ParticipantService.java
Effi-BE-fin/src/main/java/com/example/effi/service/RoutineService.java
Effi-BE-fin/src/main/java/com/example/effi/service/ScheduleService.java
Effi-BE-fin/src/main/java/com/example/effi/service/TagScheduleService.java
Effi-BE-fin/src/main/java/com/example/effi/service/TagService.java
Effi-BE-fin/src/main/resources/jwt.yaml

FEAT : Schedule service

---

Effi-BE-fin/src/main/java/com/example/effi/config/JwtAuthenticationEntryPoint.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/ApiResponse.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/Category.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/Dept.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/Employee.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/Group.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/GroupEmp.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/Participant.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/Routine.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/Schedule.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/Tag.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/TagSchedule.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/Timezone.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/TimezoneEmp.java
Effi-BE-fin/src/main/java/com/example/effi/handler/ExceptionResponseHandler.java

Column 어노테이션 옆에 nullable = false 추가

Fix : Entity 제약조건 NotNull 추가  

---

.idea/dataSources.xml
.idea/misc.xml
Effi-BE-fin/build.gradle
Effi-BE-fin/src/main/resources/application.properties

Feat: Add Swagger for API documentation

---

Effi-BE-fin/src/main/java/com/example/effi/controller/EmployeeController.java
Effi-BE-fin/src/main/resources/application.properties

token exceptionResponseHandler 와 jwt entrypoint 등 작동 테스트 완료

Improve : token error handler 완성

---

Effi-BE-fin/src/main/java/com/example/effi/config/SecurityConfig.java
Effi-BE-fin/src/main/java/com/example/effi/controller/MyPageController.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/MyPageRequestDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/MyPageResponseDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/TimezoneEmpDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/TimezoneEmp.java
Effi-BE-fin/src/main/java/com/example/effi/repository/DeptRepository.java
Effi-BE-fin/src/main/java/com/example/effi/repository/MyPageRepository.java
Effi-BE-fin/src/main/java/com/example/effi/repository/TimezoneEmpRepository.java
Effi-BE-fin/src/main/java/com/example/effi/repository/TimezoneRepository.java
Effi-BE-fin/src/main/java/com/example/effi/service/MyPageService.java
Effi-BE-fin/src/main/java/com/example/effi/service/MyPageServiceImpl.java
Effi-BE-fin/src/main/resources/application.properties

TimezoneEmp에 defaultTimezone 칼럼 추가

Refactor : TimezoneEmpDTO and MyPageService

---

Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/Group.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/Schedule.java

스케쥴 테이블과 그룹 테이블에 생성시간과 수정시간 컬럼 추가

Fix : add created and updated column

---

Effi-BE-fin/src/main/java/com/example/effi/controller/MyPageController.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/MyPageUpdateDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/TimezoneEmp.java
Effi-BE-fin/src/main/java/com/example/effi/repository/TimezoneEmpRepository.java
Effi-BE-fin/src/main/java/com/example/effi/service/MyPageService.java

Feat : Mypage default timezone update

---

Effi-BE-fin/src/main/java/com/example/effi/config/JwtAuthenticationEntryPoint.java
Effi-BE-fin/src/main/java/com/example/effi/config/JwtAuthenticationFilter.java
Effi-BE-fin/src/main/java/com/example/effi/config/TokenProvider.java
Effi-BE-fin/src/main/java/com/example/effi/controller/EmployeeController.java
Effi-BE-fin/src/main/java/com/example/effi/controller/GroupController.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/SignInResponse.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/Employee.java
Effi-BE-fin/src/main/java/com/example/effi/domain/Entitiy/RefreshToken.java
Effi-BE-fin/src/main/java/com/example/effi/repository/RefreshTokenRepository.java
Effi-BE-fin/src/main/java/com/example/effi/service/EmployeeService.java

refresh token 기능을 위해 token provider, security config, refreshtoken entity등 추가

Feat : refresh Token 기능 구현

---

Effi-BE-fin/src/main/java/com/example/effi/controller/ParticipantController.java
Effi-BE-fin/src/main/java/com/example/effi/repository/EmployeeRepository.java
Effi-BE-fin/src/main/java/com/example/effi/repository/GroupEmpRepository.java
Effi-BE-fin/src/main/java/com/example/effi/service/EmployeeService.java
Effi-BE-fin/src/main/java/com/example/effi/service/GroupService.java

- employee service
- group service
위 파일 각각에서 원하는 그룹과 부서에 해당하는 사람들의 empId(Id)를 리턴하는 함수 추가
- participant ctrl에서 부서에 해당하는 사람들 참여자 추가 생성 (Test 함)
- participant ctrl에서 그룹에 해당하는 사람들 참여자 추가 생성하였으나, 그룹 생성 하는 방법이 모호해서 테스트 못함

Feat: participant ctrl - add func

---

Effi-BE-fin/src/main/java/com/example/effi/config/SwaggerConfig.java
Effi-BE-fin/src/main/resources/application.properties

Feat : add SwaggerConfig

---

Effi-BE-fin/build.gradle
Effi-BE-fin/src/main/java/com/example/effi/controller/ChatController.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/ScheduleTags.java
Effi-BE-fin/src/main/resources/application.properties

ai tag 를 위한 Spring AI 코드 추가, ScheduleTags, ChatController 등등

Feat : ai tag 기능 추가

---

Effi-BE-fin/src/main/java/com/example/effi/controller/EmailController.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/GroupDTO.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/GroupResponseDTO.java
Effi-BE-fin/src/main/java/com/example/effi/service/EmailService.java
Effi-BE-fin/src/main/java/com/example/effi/service/GroupService.java
Effi-BE-fin/src/main/resources/application.properties

일정 시간 알림 빼고는 구현 
- 시간에 맞춰 전송하는 것이 구현 안됌 (그냥 전송)

Fix: email ctrl

---

Effi-BE-fin/src/main/java/com/example/effi/config/TokenProvider.java
Effi-BE-fin/src/main/java/com/example/effi/controller/EmployeeController.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/GlobalResponse.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/SignOutRequest.java
Effi-BE-fin/src/main/java/com/example/effi/service/EmployeeService.java
Effi-BE-fin/src/main/resources/application.properties

로그아웃 구현. 단 access 토큰은 로컬에서 삭제, refresh token 만 서버단에서 비활성화 시키는 것으로구현

Feat : SignOut

---

Effi-BE-fin/src/main/java/com/example/effi/controller/EmployeeController.java

Refactor : SignOut

---

.idea/workspace.xml
Effi-BE-fin/src/main/java/com/example/effi/controller/SearchController.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/SearchResponseDTO.java
Effi-BE-fin/src/main/java/com/example/effi/repository/TagScheduleRepository.java
Effi-BE-fin/src/main/java/com/example/effi/service/MyPageService.java
Effi-BE-fin/src/main/java/com/example/effi/service/SearchService.java

제목, 태그 , 카테고리로 일정 검색 가능
일정 검색 시 포함된 태그이름들도 함께 return

Refactor : search schedules by title,tag,category

---

Effi-BE-fin/src/main/java/com/example/effi/controller/EmployeeController.java
Effi-BE-fin/src/test/java/com/example/effi/controller/AuthControllerTest.java
Effi-BE-fin/src/test/java/com/example/effi/service/AuthServiceTest.java

AuthServiceTest 구현
정상 로그인, 없는 사번, 비밀번호 불일치

Test : 로그인 서비스 테스트 구현

---

Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/TagScheduleResponseDTO.java
Effi-BE-fin/src/main/java/com/example/effi/service/TagScheduleService.java
Effi-BE-fin/src/main/java/com/example/effi/service/TagService.java
Effi-BE-fin/src/test/java/com/example/effi/controller/TagControllerTest.java
Effi-BE-fin/src/test/java/com/example/effi/repository/TagScheduleRepositoryTest.java
Effi-BE-fin/src/test/java/com/example/effi/service/TagScheduleServiceTest.java
Effi-BE-fin/src/test/java/com/example/effi/service/TagServiceTest.java

Tag Controller, Service Test / TagSchedule Repository, Service Test 완료

Feat : Tag / TagSchedule Test

---

Effi-BE-fin/src/test/java/com/example/effi/repository/GroupEmpRepositoryTest.java

group emp repository test 실패 케이스

Test : GroupEmpRepo Test 실패 케이스 추가

---

Effi-BE-fin/src/main/java/com/example/effi/controller/EmployeeController.java

글로벌 msg 와 데이터 내부 msg 동일한 부분 수정

Fix : employeeController 반환 수정

---

Effi-BE-fin/src/main/java/com/example/effi/config/SecurityConfig.java

cors 를 위한 코드 securityconfig 에 추가

Feat : add cors SecurityConfig

---

Effi-BE-fin/src/main/resources/application.properties
Effi-FE-fin/src/services/axios.js
Effi-FE-fin/src/stores/auth.js
Effi-FE-fin/src/views/LoginView.vue

auth.js 와 LoginView.vue 작성과 수정

Feat : 로그인 프론트엔드 구현

---

Effi-BE-fin/src/main/java/com/example/effi/controller/GroupController.java
Effi-BE-fin/src/main/java/com/example/effi/controller/TagController.java
Effi-BE-fin/src/main/java/com/example/effi/service/TagScheduleService.java
Effi-BE-fin/src/main/java/com/example/effi/service/TagService.java
Effi-BE-fin/src/main/resources/application.properties
Effi-FE-fin/package-lock.json
Effi-FE-fin/package.json
Effi-FE-fin/src/components/GroupList.vue
Effi-FE-fin/src/components/ScheduleTable.vue
Effi-FE-fin/src/router/index.js
Effi-FE-fin/vite.config.js

- Add GroupList.vue, ScheduleTable.vue
- Implement getGroup function in GroupController
- Implement getTag function in TagController, TagSchedulerService, TagService

Feat: Add new Vue component and Spring group/tag query functions

---

Effi-FE-fin/src/components/HomeHeader.vue
Effi-FE-fin/src/router/index.js
Effi-FE-fin/src/stores/auth.js

라우터에서 로그인 상태 확인 후 로그인 되지 않은 경우 로그인 페이지로 이동,
로그아웃 시 로그인 페이지로 이동

Feat : 로그인 상태 확인 및 로그아웃 시 로그인 페이지로 이동 기능 추가

---

Effi-BE-fin/src/main/java/com/example/effi/controller/MyPageController.java
Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/MyPageTimezoneDTO.java
Effi-BE-fin/src/main/java/com/example/effi/repository/MyPageRepository.java
Effi-BE-fin/src/main/java/com/example/effi/service/MyPageService.java
Effi-BE-fin/src/main/resources/application.properties
Effi-FE-fin/src/components/MyPageUpdate.vue
Effi-FE-fin/src/components/SearchItem.vue
Effi-FE-fin/src/components/SearchList.vue
Effi-FE-fin/src/filters/filters.js
Effi-FE-fin/src/router/index.js
Effi-FE-fin/src/views/MyPageView.vue
Effi-FE-fin/src/views/SearchView.vue

Feat : MyPage View

---

Effi-BE-fin/src/main/resources/application.properties
Effi-FE-fin/src/components/ScheduleTableWithCategory.vue
Effi-FE-fin/src/components/SelectCategory.vue
Effi-FE-fin/src/router/index.js
Effi-FE-fin/src/views/CategoryScheduleView.vue

- ScheduleTableWithCategory -> 카테고리 설정에 따라 출력되는게 달라짐 (카테고리별) , 디폴트는 전체
- ScheduleTable -> 그냥 전체 일정 출력
- SelectCategory -> 카테고리 선택 가능 component
- CategoryScheduleView -> ScheduleTableWithCategory & SelectCategory로 구성된 view로 구현내용 확인 가능 
링크는 `/category` 입니다.

Feat: Add category component

---

Effi-FE-fin/src/components/SearchItem.vue
Effi-FE-fin/src/components/SearchList.vue
Effi-FE-fin/src/components/StatusFilter.vue
Effi-FE-fin/src/components/WeekNavigator.vue
Effi-FE-fin/src/filters/filters.js
Effi-FE-fin/src/views/SearchView.vue

Search View 디자인 + 서치 창으로 바로 결과 안나오는것 수정 예정

FEAT : SearchView vue

---

Effi-FE-fin/src/components/LeftSidebar.vue

Feat : 사이드바 로그아웃 기능 추가

---

Effi-FE-fin/src/components/TagAdd.vue

Fix : 태그 추가 기능 수정

---

Effi-FE-fin/src/components/EventDialog.vue
Effi-FE-fin/src/components/RoutineModal.vue
Effi-FE-fin/src/components/ScheduleModal.vue
Effi-FE-fin/src/components/TagAdd.vue
Effi-FE-fin/src/views/ScheduleTestView.vue

아래와 같은 오류가 계속 발생하는 중...
POST http://localhost:8080/api/schedule/add 500 (Internal Server Error)
dispatchXhrRequest @ xhr.js:188
xhr @ xhr.js:15
dispatchRequest @ dispatchRequest.js:51
_request @ Axios.js:173
request @ Axios.js:40
httpMethod @ Axios.js:212
wrap @ bind.js:5
submit @ EventDialog.vue:238
(익명) @ EventDialog.vue:8
cache.<computed>.cache.<computed> @ runtime-dom.esm-bundler.js:1476
callWithErrorHandling @ runtime-core.esm-bundler.js:195
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:202
invoker @ runtime-dom.esm-bundler.js:696
프레임 11개 더 표시
간략히 보기
EventDialog.vue:254 Error submitting form: Failed to add schedule: For input string: "anonymous"
submit @ EventDialog.vue:254
await in submit(비동기)
(익명) @ EventDialog.vue:8
cache.<computed>.cache.<computed> @ …

Feat: ScheduleModal and routine modal 생성 및 연동/ 스케줄 모달은 태그 이슈로 아직 미완성

---

Effi-FE-fin/src/components/CreateGroupModal.vue
Effi-FE-fin/src/components/DeptModal.vue
Effi-FE-fin/src/components/GroupModal.vue
Effi-FE-fin/src/components/HomeHeader.vue
Effi-FE-fin/src/components/RoutineModal.vue
Effi-FE-fin/src/components/ScheduleModal.vue
Effi-FE-fin/src/components/TimezoneModal.vue
Effi-FE-fin/src/components/VCalendar.vue
Effi-FE-fin/src/views/MyPageView.vue
Effi-FE-fin/src/views/SearchView.vue

eventdialog /  tagadd 제외하고 axios -> axiosInstance 방식으로 수정 완료

Refactor : axios to axiosInstance

---

Effi-FE-fin/src/components/EventDialog.vue
Effi-FE-fin/src/components/TagAdd.vue

직원 검색 및 선택을 통한 참가자 id가 안넘어가서 추가가 안됨. 아래와 같은 오류 발생
POST http://localhost:8080/api/participant/add 500 (Internal Server Error)
dispatchXhrRequest @ xhr.js:188
xhr @ xhr.js:15
dispatchRequest @ dispatchRequest.js:51
Promise.then(비동기)
_request @ Axios.js:149
request @ Axios.js:40
httpMethod @ Axios.js:212
wrap @ bind.js:5
submit @ EventDialog.vue:242
await in submit(비동기)
(익명) @ EventDialog.vue:7
cache.<computed>.cache.<computed> @ runtime-dom.esm-bundler.js:1476
callWithErrorHandling @ runtime-core.esm-bundler.js:195
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:202
invoker @ runtime-dom.esm-bundler.js:696
프레임 11개 더 표시
간략히 보기
EventDialog.vue:251 Error submitting form: Failed to add participant: The given id must not be null

Fix: eventdialog and tagadd 오류 수정

---

Effi-FE-fin/src/components/TagAdd.vue
Effi-FE-fin/src/services/axios.js

TagAdd 의 클릭시 태그 리스트에서 삭제, 에러 표현 방식 alert 에서 message 출력으로 수정, axios 에러 한줄 수정을 통해 accessToken 갱신 기능

Fix : TagAdd and axios

---

Effi-BE-fin/src/main/java/com/example/effi/config/TaskSchedulerConfig.java
Effi-BE-fin/src/main/java/com/example/effi/controller/EmailController.java
Effi-BE-fin/src/main/java/com/example/effi/service/EmailService.java
Effi-BE-fin/src/main/java/com/example/effi/service/ScheduleService.java

- 이메일 컨트롤러 추가할 필요 없이 스케줄 삽입 + 수정시 자동으로 메일 함수 실행됩니다,,,,,,,,,,, 이얏호~

Fix: Email func

---

Effi-BE-fin/src/main/java/com/example/effi/EffiApplication.java
Effi-BE-fin/src/main/java/com/example/effi/service/EmailService.java
Effi-BE-fin/src/main/resources/application.properties

메일때문에
@EnableAsync <- 추가 햇슴둥..

Fix : groupMail

---

Effi-BE-fin/src/main/java/com/example/effi/controller/ScheduleController.java
Effi-BE-fin/src/main/java/com/example/effi/service/ScheduleService.java
Effi-FE-fin/src/components/AllSchedulesList.vue
Effi-FE-fin/src/components/ParticipantsTodaySchedule.vue
Effi-FE-fin/src/components/SearchList.vue

Refacotor: Group Participants의 오늘 일정 조회시 카테고리에 따른 색 구분

---

Effi-BE-fin/src/main/java/com/example/effi/domain/DTO/ScheduleResponseDTO.java
Effi-FE-fin/src/App.vue
Effi-FE-fin/src/components/CreateGroupModal.vue
Effi-FE-fin/src/components/SelectCategory.vue
Effi-FE-fin/src/components/TimezoneModal.vue
Effi-FE-fin/src/components/VCalendar.vue
Effi-FE-fin/src/components/VSidebar.vue
Effi-FE-fin/src/services/axios.js
Effi-FE-fin/src/views/AllSchedulesView.vue
Effi-FE-fin/src/views/GroupParticipantsView.vue
Effi-FE-fin/src/views/GroupSchedulesView.vue
Effi-FE-fin/src/views/HomeView.vue
Effi-FE-fin/src/views/MyPageView.vue
Effi-FE-fin/src/views/SearchView.vue
Effi-FE-fin/src/views/TagStatisticsView.vue

Fix: Timezone Component
디자인 배치 수정 등..

Fix: VSidebar VCalendar App.vue 연결 로직 수정

---

Effi-FE-fin/src/components/AllSchedulesList.vue
Effi-FE-fin/src/components/GroupSchedulesList.vue
Effi-FE-fin/src/components/SearchList.vue

Design : Schedule List 의 종료날짜 추가 & tag Color 랜덤-> 고정
